name: smile
favicon: null
layout_spectrum: 0.49833
typography_spectrum: 0.9039354929700494
title: Smile
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b7693e'
    - '#f7beac'
    - '#e29271'
    - '#c34133'
  brandStrength: 0.1875
  lightness: 0.09681082656607032
  saturation: 0.9679577718488872
  rhythmicContrast: 0.25896111293695867
purpose: []
